services:
  # PostgreSQL Database
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-LOCAL}
      POSTGRES_USER: ${DB_USER:-alaric}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-alaric}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/createTable.sql:/docker-entrypoint-initdb.d/01-createTable.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alaric -d LOCAL"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: 'admin@syntra.com'
        PGADMIN_DEFAULT_PASSWORD: 'markSuperUser72910'
    ports:
        - 16543:80

volumes:
  postgres_data: